### ISSUE TITLE
Don't escape step code strings

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-phoenix#100]
AFAIK we need this only for the Studio, so let pass this functionality to the decorators (and don't do it in the default decorators
![escape](https://cloud.githubusercontent.com/assets/453071/10305106/ee1a922c-6c26-11e5-9ef0-0cca90a85f52.png)
)

**Comment by inikulin** [comment]
ping @kirovboris

**Comment by kirovboris** [comment]
Ok, i'll fix it ASAP.
