### ISSUE TITLE
Add eslint rules for the arrow syntax

### ISSUE THREAD

**Issue by LavrovArtem** [superroma/testcafe-phoenix#108]
```
"babel/arrow-parens": [2, "as-needed"]
"arrow-spacing": [2, { "before": true, "after": true }]
"prefer-arrow-callback": 2
```
see: superroma/testcafe-hammerhead#173

```babel/arrow-parens``` requires https://github.com/babel/eslint-plugin-babel

**Comment by inikulin** [comment]
@LavrovArtem Seems like you've used another rules, e.g. `babel/arrow-parens`. Moreover it's requires plugin.

**Comment by inikulin** [comment]
I'm working on this.
