### ISSUE TITLE
Reporter failes when a failed assertion contains html markup

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-phoenix#127]
Reporter fails with an error in the following situation:
```js
var div1 = document.getElementById('div1');
var div2 = document.getElementById('div2');

eq(div1, div2);
```

In you compare jQuery objects `eq($(div1), $(div2));` reporter writes:
```json
expected: []
actual: []
```

**Comment by inikulin** [comment]
\cc @kirovboris Seems like in this case diffs fails

**Comment by inikulin** [comment]
ping @kirovboris

**Comment by kirovboris** [comment]
This error causes on client side, reporter mustn't receive html markup, we have to escape html in src/client/runner/api/assertions.js.

**Comment by inikulin** [comment]
\cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
I'll research the issue soon. It works with the 15.1 version, and there were no changes on client in this mechanism. We should understand why it was working before and how it should work now

**Comment by inikulin** [comment]
@AlexanderMoskovkin There were changes on server side, now we use HTML for templates markup. So, HTML content should be escaped to be presented as the text

**Comment by inikulin** [comment]
It could be easily done with:
```js
function escapeHTML(s) { 
    return s.replace(/&/g, '&amp;')
            .replace(/"/g, '&quot;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
}
```

**Comment by kirovboris** [comment]
It works with the 15.1, because i had made the escaping all markdown messages on the server side. It was necessary for markdown module. There were some problems with rendering html.

**Comment by helen-dikareva** [comment]
I'm working on this
