### ISSUE TITLE
Reorganize client-side scripts

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-phoenix#25]
Split scripts to:
- core.js (or testcafe_core.js)
- runner.js (or testcafe_runner.js)
- ui.js (or testcafe_ui.js)

Each module has documented API. Modules are available via a global variable in `window`. 

/cc @inikulin

**Comment by inikulin** [comment]
Since we will preserve dirs structure in FS we will have:
`core/index.js`
`ui/index.js`
`runner/index.js`

Meanwhile, they will be mapped to the another names by assets manager:
https://github.com/superroma/testcafe-phoenix/blob/master/src/index.js#L24

**Comment by AlexanderMoskovkin** [comment]
test
