### ISSUE TITLE
Browser job completion mechanism is incorrect.

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-phoenix#33]
There are two ways which leads to the job completion:

1. All job's test runs are finished.
2. Job's task was aborted 

In the first scenario browser requests status an we query job in the front of the queue for the next test run. If job doesn't contain pending test runs any more it returns `null` and raises `done` event. `done` event handler in the `BrowserConnection` removes job from the queue. But since `BrowserConnection.getStatus()` already queried queue browser goes to the `idle` state. It will query status anyway, however it leads to the unecessary delay.

The second scenario has more complicated problems. Task calls `abort()` for each of it's jobs. `abort()` just cleans pending test runs queue. So, from the browsers perspective we will have the same issue as described for the first case. The other issue for this approach is that we still relay on `done` event for the abortion scenario which is really fragile. `done` event on all jobs will trigger `done` event for the task. Which is wrong. Currently we rely on the fact that adopting code will call `task.removeAllListeners()` immediately after `task.abort()` which is definetly uncool.

The proposal is:
* Do not rely on the `done` event of the job in the `BrowserConnection`. Use the following algorithm instead: 
  1. If `jobQueue` is empty then switch browser to the `idle` state and abort these steps.
  2. Try query job in the front of the queue. If it returns `null` then shift the queue and repeat this step. Else pass returned test run to the browser.
   
* `task.abort()` should immediately remove all task's jobs from the appropriate browser connections.

**Comment by inikulin** [comment]
Thinking of this more I think we have all control flow messed up currently.
I propose following changes:

1.  `BrowserJob` should be considered `done` not then it's `nextTestRunUrl` getter is triggered and `testRunQueue` is empty. Instead we should have `pendingTestRunCount` variable which is initially equals to the `testRunQueue.length` and gets decremented once `BrowserJob` raises `test-run-done` event. Once it's equal to 0 we'll emit `done` event for the job.
2. We should turn `nextTestRunUrl` in both `BrowserJob` and `BrowserConnection` into the function and name it `popNextTestRunUrl`. This will be definetly more correct in terms of semantics.
3. `BrowserJob` should provide `hasQueuedTestRuns` property. `BrowserConnection` should check this property once it popped next test run url from the job, and if it's `false` then shift it's `jobQueue`.
4. `BrowserJob.abort()` should set `BrowserJob.aborted` flag to `true`. This flag will disable all events for the job. So, both job and related task will remain silent.
5. Meanwhile `Task.abort()` should call `abort()` for all it's jobs and immediately remove jobs from the corresponding `BrowserConnection`'s. For this purpose we will use `pendingBrowserJobsMap` object which is a instance of `Map`. The key of the map is the job and the value is browser connection. Usage of the `Map` gives us two benefits: we will be able to easily remove completed jobs without boilerplate code which is required for such operation for arrays and we will instantly have browser connection related to job which is helpful for the `abort()`.

\cc @kirovboris @AlexanderMoskovkin @churkin I would like to know your opinion. Is this somehow clear and makes sense for you?

**Comment by kirovboris** [comment]
I think it's definitely more clearly and has more semantics.

**Comment by AlexanderMoskovkin** [comment]
The last variant looks nice.
