### ISSUE TITLE
Setup AppVeyor for the server tests

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-phoenix#34]
In addtion to Travis it would be nice to have [AppVeyor](http://www.appveyor.com/) tests for server, so will be able to test Windows specific things. @AlexanderMoskovkin Is it possible to teach our bot accumulate test results from both Travis and AppVeyor?

**Comment by AlexanderMoskovkin** [comment]
I'll research this

**Comment by AlexanderMoskovkin** [comment]
In fact we have no browser-specific server tests now. We will can reopen the issue if necessary.

**Comment by inikulin** [comment]
@AlexanderMoskovkin it's not about browser-specific, but Windows-specific things in our code. Let's keep it open for now.

**Comment by AlexanderMoskovkin** [comment]
sure, it was a misprint

**Comment by inikulin** [comment]
I don't think we need it. Closing for now.
