### ISSUE TITLE
Get rid of 'jobOwnerToken' and 'jobUid' in the code

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-phoenix#47]
As a continuation of the superroma/testcafe-hammerhead#65 we need to remove `jobUid` and `jobOwnerToken` from the client code and replace it with the `sessionId`. We need to do that for the tests and server (if we have anything there) as well.

**Comment by AlexanderMoskovkin** [comment]
FYI: we have `jobUid` just in the client-tests. We will get rid of this and close the issue after hammerhead will be published in npm
