### ISSUE TITLE
Implement QUnit CI

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-phoenix#53]

**Comment by AlexanderMoskovkin** [comment]
We are ready to implement the issue but we have green tests only in 4 browsers now: ff, chrome, ie11, ie10.
- MSEdge: one failed test (because of the hammerhead bug. We will create an issue for that)
- ios (safari, ipad, ios): about 5 failed tests
- ie9: several failed tests
- android: 2 failed tests

We can implement the issue now and add just 4 browsers to qunit-harness settings. Then we create issues to add other browsers. Or we can fix all the problems in all browsers locally first and then close this issue (it can take 2 or more days for 2 developers). @inikulin what do you think?

**Comment by inikulin** [comment]
I like the first option: get things up and running now at least in 4 browsers, then create separate issues for each browser.
