### ISSUE TITLE
Review rules after upgrading eslint to 1.x

### ISSUE THREAD

**Issue by AndreyBelym** [superroma/testcafe-phoenix#58]
From [Migrating to 1.0.0](http://eslint.org/docs/user-guide/migrating-to-1.0.0.html):
The most important difference in v1.0.0 is that all rules are off by default. When using --init, your configuration file will automatically include the following line:
```js
{
    "extends": "eslint:recommended"
}
```
This setting mimics some of the default behavior from 0.x, but not all. 
These rules are no longer on by default, so you should review your settings to ensure they are still as you expect:
no-alert
no-array-constructor
no-caller
no-catch-shadow
no-empty-label
no-eval
no-extend-native
no-extra-bind
no-extra-strict
no-implied-eval
no-iterator
no-label-var
no-labels
no-lone-blocks
no-loop-func
no-multi-spaces
no-multi-str
no-native-reassign
no-new
no-new-func
no-new-object
no-new-wrappers
no-octal-escape
no-process-exit
no-proto
no-return-assign
no-script-url
no-sequences
no-shadow
no-shadow-restricted-names
no-spaced-func
no-trailing-spaces
no-undef-init
no-underscore-dangle
no-unused-expressions
no-use-before-define
no-with
no-wrap-func
camelcase
comma-spacing
consistent-return
curly
dot-notation
eol-last
eqeqeq
key-spacing
new-cap
new-parens
quotes
semi
semi-spacing
space-infix-ops
space-return-throw-case
space-unary-ops
strict
yoda
See also: the [full diff](https://github.com/eslint/eslint/commit/e3e9dbd9876daf4bdeb4e15f8a76a9d5e6e03e39#diff-b01a5cfd9361ca9280a460fd6bb8edbbL1) where the defaults were changed.

List of recommended rules:
comma-dangle - disallow or enforce trailing commas (recommended)
no-cond-assign - disallow assignment in conditional expressions (recommended)
no-console - disallow use of console in the node environment (recommended)
no-constant-condition - disallow use of constant expressions in conditions (recommended)
no-control-regex - disallow control characters in regular expressions (recommended)
no-debugger - disallow use of debugger (recommended)
no-dupe-args - disallow duplicate arguments in functions (recommended)
no-dupe-keys - disallow duplicate keys when creating object literals (recommended)
no-duplicate-case - disallow a duplicate case label. (recommended)
no-empty-character-class - disallow the use of empty character classes in regular expressions (recommended)
no-empty - disallow empty statements (recommended)
no-ex-assign - disallow assigning to the exception in a catch block (recommended)
no-extra-boolean-cast - disallow double-negation boolean casts in a boolean context (recommended)
no-extra-semi - disallow unnecessary semicolons (recommended)
no-func-assign - disallow overwriting functions written as function declarations (recommended)
no-inner-declarations - disallow function or variable declarations in nested blocks (recommended)
no-invalid-regexp - disallow invalid regular expression strings in the RegExp constructor (recommended)
no-irregular-whitespace - disallow irregular whitespace outside of strings and comments (recommended)
no-negated-in-lhs - disallow negation of the left operand of an in expression (recommended)
no-obj-calls - disallow the use of object properties of the global object (Math and JSON) as functions (recommended)
no-regex-spaces - disallow multiple spaces in a regular expression literal (recommended)
no-sparse-arrays - disallow sparse arrays (recommended)
no-unreachable - disallow unreachable statements after a return, throw, continue, or break statement (recommended)
use-isnan - disallow comparisons with the value NaN (recommended)
valid-typeof - Ensure that the results of typeof are compared against a valid string (recommended)
no-fallthrough - disallow fallthrough of case statements (recommended)
no-octal - disallow use of octal literals (recommended)
no-redeclare - disallow declaring the same variable more than once (recommended)
no-delete-var - disallow deletion of variables (recommended)
no-undef - disallow use of undeclared variables unless mentioned in a /*global */ block (recommended)
no-unused-vars - disallow declaration of variables that are not used in the code (recommended)
no-mixed-spaces-and-tabs - disallow mixed spaces and tabs for indentation (recommended)

We need to review .eslintrc for inheriting default rules and manually adding rules that were excluded from defaults (e.g. no-undef, semi and so).

**Comment by inikulin** [comment]
We need this for the browser-natives as well

**Comment by AlexanderMoskovkin** [comment]
Yes, @AndreyBelym have created issues for all our projects
