### ISSUE TITLE
Get rid of the old browser inactivity detection mechanism

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-phoenix#66]

**Comment by inikulin** [comment]
NOTE: It's quite important to do that ASAP, because long tests will cause browser disconnection right now, since we've removed old ping mechanism.

**Comment by inikulin** [comment]
@AlexanderMoskovkin Refactor shared browser-related functionality into `src/client/browser/index.js` as we discussed. And move idle page code to `src/client/browser/idle-page`

**Comment by AlexanderMoskovkin** [comment]
We should not go to the Idle page between tests now. I'll do it with this refactoring
