### ISSUE TITLE
We need to figure out coloring for the errors in reports.

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-phoenix#68]
We need some kind of spike project which will generate message for all errors in context of different reporters to figure out best coloring for the `ttyDecorator`.
\cc @kirovboris @VasilyStrelyaev

**Comment by inikulin** [comment]
Now then we have design viewer let's work on this issue \cc @kirovboris @MargaritaLoseva @VasilyStrelyaev @churkin @AlexanderMoskovkin @AndreyBelym @arubtsov @LavrovArtem

**Comment by inikulin** [comment]
Now, then all report-related bugs are fixed we need to resolve this one \cc @VasilyStrelyaev @MargaritaLoseva

**Comment by VasilyStrelyaev** [comment]
Sure, let me play around with colors a bit

**Comment by inikulin** [comment]
@VasilyStrelyaev You can change them in https://github.com/superroma/testcafe-phoenix/blob/master/src/reporters/errors/decorators/tty.js FYI

**Comment by VasilyStrelyaev** [comment]
yep, thx, I figured it out

**Comment by inikulin** [comment]
@VasilyStrelyaev Possible chalk styles can be found here: https://github.com/chalk/chalk

**Comment by VasilyStrelyaev** [comment]
that's what I've also figured out =)

**Comment by VasilyStrelyaev** [comment]
Try this one
https://gist.github.com/VasilyStrelyaev/7f9388870eb92d4432ee

**Comment by VasilyStrelyaev** [comment]
not so good with <strong> (I can't figure how to show it yet)

**Comment by inikulin** [comment]
Drag and drop images to the comment text area to insert them

**Comment by VasilyStrelyaev** [comment]
oh, cool!
then, I have more than one to choose from
1)
![image](https://cloud.githubusercontent.com/assets/11459924/10304758/c8a72aca-6c24-11e5-8bc9-eedae10ab594.png)
2)
![image](https://cloud.githubusercontent.com/assets/11459924/10304797/02686f3a-6c25-11e5-9211-c736ad978ff5.png)

**Comment by inikulin** [comment]
@VasilyStrelyaev Please, get the latest version, it has fixed formatting. I like the second though.

**Comment by inikulin** [comment]
We need to separate errors somehow. I've added highlighting (locally for now) of the user agent string to achieve this. Here are couple of examples in shitty windows cmd and cmder (because I was too lazy to switch between mac and win machines :tired_face:)

**1.**
![win1](https://cloud.githubusercontent.com/assets/453071/10305026/5eff2030-6c26-11e5-9e43-06f764918a1a.png)
![term1](https://cloud.githubusercontent.com/assets/453071/10305029/635b7bba-6c26-11e5-8313-db955f8fe05f.png)

**2.**
![win2](https://cloud.githubusercontent.com/assets/453071/10305034/6cf714c2-6c26-11e5-8a8a-74c439a6c1db.png)
![term2](https://cloud.githubusercontent.com/assets/453071/10305035/6f88584a-6c26-11e5-8dca-4a8a08d8ad4c.png)

\cc @kirovboris @AlexanderMoskovkin @churkin @arubtsov @LavrovArtem @miherlosev @MargaritaLoseva @AndreyBelym @helen-dikareva

**Comment by inikulin** [comment]
@VasilyStrelyaev Can you paste here tty code for your second sample?

**Comment by VasilyStrelyaev** [comment]
https://gist.github.com/VasilyStrelyaev/affda1394c2b3589a62f

**Comment by inikulin** [comment]
How about this one:
![term3](https://cloud.githubusercontent.com/assets/453071/10307071/51bebe86-6c34-11e5-8990-88dc1834d89a.png)
![win3](https://cloud.githubusercontent.com/assets/453071/10307074/52c61aa4-6c34-11e5-946a-74d3e4ae9e22.png)

**Comment by inikulin** [comment]
Increased spaces, removed styling for step name

![term4](https://cloud.githubusercontent.com/assets/453071/10307242/f802e23a-6c35-11e5-9867-64cc4dde25f6.png)

**Comment by inikulin** [comment]
Grayed user agent, but doesn't looks like errors for me
![term5](https://cloud.githubusercontent.com/assets/453071/10307300/792bcc5a-6c36-11e5-8336-6d08ef7a891e.png)

**Comment by inikulin** [comment]
Minimal reporter:
![term6](https://cloud.githubusercontent.com/assets/453071/10307369/0a477a90-6c37-11e5-9b8a-62d128f1ad09.png)
